### ISSUE TITLE
main.ArtistController.java class is missing

### ISSUE THREAD

**Issue by letcharren** [nmaguirre/riocuartobandasderock#11]
implements ArtistControler

**Comment by nmaguirre** [comment]
Please check your createArtist routine (and for this matter, all routines in your controller). You are not setting the right HTTP status response code. See

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

for reference. 

Cheers,

Naza

**Comment by letcharren** [comment]
@nmaguirre I have a question. HTTP status code must be in bootstrap or SongController?

**Comment by nmaguirre** [comment]
Wherever you handle the construction of the response object.

Cheers,

N
