### ISSUE TITLE
dao.SongDAO is missing.

### ISSUE THREAD

**Issue by guttlein** [nmaguirre/riocuartobandasderock#12]

**Comment by letcharren** [comment]
@jortolano @guttlein Missing declare the new functions of SongDaoImpl in SongDAO

**Comment by jortolano** [comment]
@letcharren I removed the label because the problem did not exist

**Comment by letcharren** [comment]
the problem existed, Nazareno remove the @override in the SongDaoImpl methods in commit 30c18eb, and after you've added the declaration of SongDAO methods  in commit 010e693
