### ISSUE TITLE
SongController is missing

### ISSUE THREAD

**Issue by lucaspalacios** [nmaguirre/riocuartobandasderock#13]

**Comment by lucaspalacios** [comment]
Implements the song controller class

**Comment by lucaspalacios** [comment]
14d9b01

**Comment by lucaspalacios** [comment]
8b18889

**Comment by nmaguirre** [comment]
It seems your controller's routines are not setting the right HTTP status response codes. Please make sure they do. See

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

for reference.

Cheers,

Naza

**Comment by lucaspalacios** [comment]
Okay @nmaguirre , thanks for the help!

**Comment by lucaspalacios** [comment]
812068d

**Comment by DanielSanchez94** [comment]
Resolve the appropriate changes so that we can run scenarios, urgently.

**Comment by lucaspalacios** [comment]
We're on it @DanielSanchez94

**Comment by lucaspalacios** [comment]
267bcaa

**Comment by lucaspalacios** [comment]
2832128
