### ISSUE TITLE
DAO.AlbumDao in missing

### ISSUE THREAD

**Issue by dmatiasr** [nmaguirre/riocuartobandasderock#14]
DAO.AlbumDao Describes the interface with the methods of the class Album

**Comment by dmatiasr** [comment]
Describes the interface with the methods of the class Album

**Comment by MauriDV** [comment]
progress 38d69a9

**Comment by dmatiasr** [comment]
add more profiles 063045c

**Comment by MauriDV** [comment]
more profiles... ff8ac3c

**Comment by dmatiasr** [comment]
progress 139553

**Comment by dmatiasr** [comment]
progress 43de91d

**Comment by dmatiasr** [comment]
Replace params int id for String id 
and more test:
getAllAlbumsTestCase() 
ead7d17

**Comment by MauriDV** [comment]
fix profiles bd22405 c200362
add tests 0ef0a8e

**Comment by jheredia** [comment]
The implementation of the DAO returns any error in case that any of the operations failed?

**Comment by dmatiasr** [comment]
progress bd28a32, 64ed868

Ok, @jheredia and missing test throwing exceptions, we will end soon.

**Comment by dmatiasr** [comment]
8c09a6d Modified profiles:  findByReleaseDate , findByName

**Comment by MauriDV** [comment]
7733d1f add profiles of hibernate configuration

**Comment by dmatiasr** [comment]
24c3aad unnecessary comments
