### ISSUE TITLE
dao.BandDAO is missing

### ISSUE THREAD

**Issue by camicalca** [nmaguirre/riocuartobandasderock#15]

**Comment by camicalca** [comment]
dao.BandDAO Describes the interface with the methods of the class Band

**Comment by camicalca** [comment]
f9ecdda

**Comment by camicalca** [comment]
fe7f2da

**Comment by martinlopez** [comment]
Hello @camicalca and @agustinmartinez01, I recommend you make the following change , the method getBand(int id) must be getBand(String id), the id attribute should not be an int .

**Comment by martinlopez** [comment]
@camicalca @agustinmartinez01 also, you should change deleteBand(Band band) to deleteBand(String id), because you can identify that item to delete just knowing its id. Obviously, these changes should be reflected in the implementation of BandDaoImpl class.

**Comment by lucaspalacios** [comment]
Hi @camicalca and @agustinmartinez01, this class should implement a routine that finds a band by its name. It would be something like this: public Band findBandByName(string name)

I hope you can do this, because I need it for my song controller. Thanks

**Comment by camicalca** [comment]
Hi @lucaspalacios, thanks !! Ready the changes !

**Comment by lucaspalacios** [comment]
Thanksss!!  :)

**Comment by nmaguirre** [comment]
We are changing the Band class (model), to have only id, name and genre. Please update BandDAO to just consider these attributes. Please notice that 'genere' is not a valid word; use genre instead (just pointing this out because the term spread from a wronful use in the model class Band).
