### ISSUE TITLE
Implementation of Album Controller is missing

### ISSUE THREAD

**Issue by jheredia** [nmaguirre/riocuartobandasderock#17]
There is no implementation for the Album Controller.

**Comment by jheredia** [comment]
@nmaguirre I will assign this issue to myself once you add me as collaborator.

**Comment by LuuchoRocha** [comment]
I'll be with you in this :)

**Comment by nmaguirre** [comment]
Are you still working on this issue? Please make sure that your album controller routines set the right HTTP status response codes. See

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

for reference. 

Cheers,

Naza
