### ISSUE TITLE
dao.impl.BandDaoImpl is missing

### ISSUE THREAD

**Issue by agustinmartinez01** [nmaguirre/riocuartobandasderock#18]
create class and implements

**Comment by agustinmartinez01** [comment]
create class 2dff3b1

**Comment by agustinmartinez01** [comment]
headboard BandDaoImpl 6a733a6

**Comment by lbuttignol** [comment]
@agustinmartinez01 @camicalca This class should implements the BandDAO interface! Please change the line 9

```
public class BandDaoImpl {
```
with this line:

```
public class BandDaoImpl implements {  
```

**Comment by lbuttignol** [comment]
@agustinmartinez01 @camicalca  this class have a bug on createBand method

I change a line 176 : 
```
if(bandList != null || !bandList.isEmpty()){
```

with this line
```
if(!bandList.isEmpty()){
```

an the projects works. Take a look, and if that is correct make the changes ;)

**Comment by lbuttignol** [comment]
Also shoud check this lines
```
Boolean areNull = name == null && genre == null;
Boolean areEmpty = name.equals("") && genre.equals("");
```
in the case `areNull =true `  this code have a runtime error.
