### ISSUE TITLE
Merge class Genere and Genre

### ISSUE THREAD

**Issue by DanielSanchez94** [nmaguirre/riocuartobandasderock#28]

**Comment by DanielSanchez94** [comment]
issue resolved in 4be4a1a

**Comment by saiema** [comment]
- Missing a description of the issue
- The solution doesn't merge the two classes (since now there is Genre and TGenre)
- TGenre should be an enum inside Genre (probably with another name), the enum should be public static

**Comment by nmaguirre** [comment]
This isn't satisfactory yet. 'Genere' does not exist as a word. Please correct. For the time being, we will have bands composed only of an id, a name, and a genre. Remove/comment all other elements of the Band class in the model.

**Comment by nmaguirre** [comment]
Recall that 'genere' is not a valid word! Please correct all over the class.
