### ISSUE TITLE
Model. Artist is missing

### ISSUE THREAD

**Issue by GonzalezDiana** [nmaguirre/riocuartobandasderock#3]
This class represents one person that is member of a band.

**Comment by letcharren** [comment]
miissing description

**Comment by GonzalezDiana** [comment]
in progress [e5185b8]

**Comment by GonzalezDiana** [comment]
100644 - The class was renamed as "Artist", so the class "BandMember" will be a association class between Artist and Band. Band Member will have only an Artist, a Band and a list of roles.

**Comment by GonzalezDiana** [comment]
Test in commit [8e45b2f]

**Comment by GonzalezDiana** [comment]
Test setNull in [3f12dbc]

**Comment by ezensich** [comment]
Error found. The artist class must have a default constructor ( Artist() ), please correct this.

**Comment by saiema** [comment]
Resolved
