### ISSUE TITLE
dao.impl.AlbumDaoImpl is missing 

### ISSUE THREAD

**Issue by MauriDV** [nmaguirre/riocuartobandasderock#30]
implement interface AlbumDao with AlbumDaoImpl

**Comment by dmatiasr** [comment]
#14 In this issues are implementations for AlbumDaoImpl

**Comment by MauriDV** [comment]
JavaDoc comments in methods 0fe1708

**Comment by dmatiasr** [comment]
8479750 findByReleaseDate() and findByName() implements

**Comment by MauriDV** [comment]
7733d1f findByID(), getAllAlbums() and createAlbum() implements

**Comment by dmatiasr** [comment]
b38bfbb  findByReleaseDate() , case null date.

**Comment by dmatiasr** [comment]
6ccff1d updateAlbum() implementation

**Comment by MauriDV** [comment]
e32e827 implementation of deleteAlbum()

**Comment by dmatiasr** [comment]
Basic methods 629e442

**Comment by dmatiasr** [comment]
JavaDoc for code 02bf0d6

**Comment by MauriDV** [comment]
494aae8 fix date
