### ISSUE TITLE
ArtistDaoImpl not implemented

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/riocuartobandasderock#35]
ArtistDaoImpl is the implementation of a DAO for class Artist. To implement it, have a look at the Artist class (model), and use as reference the following:

https://examples.javacodegeeks.com/enterprise-java/hibernate/hibernate-jpa-dao-example/

**Comment by juanpabloRV** [comment]
<code ArtistDaoImpl.java at line 177>
"if(artistList != null || !artistList.isEmpty())"

this is not working! because artistList always is !=null.

**Comment by nmaguirre** [comment]
What part of the code are you referring to?

**Comment by juanpabloRV** [comment]
This bug  causes the file  "step_definitions.rb at line 43" fails..

**Comment by nmaguirre** [comment]
Pasting a little bit more of code:

List<Artist> artistList = query.getResultList();
			if(artistList != null || !artistList.isEmpty()){
				result = false;
			} else {
				Artist artist = new Artist(name, surname, nickname);
				currentSession.save(artist);
				result = true;
			}
			return result;

I think the purpose here is to chech whether the artist is already in the system, and if it is, return false (can't create an new artist when it's already there). I agree, the way you guys are checking it is wrong. It should be safe here to assume that artistList is not null. Please correct asap.

Cheers!

N

**Comment by ezensich** [comment]
This bug was corrected, and running artistDAO tests with an empty database, can check your correct functionality. 
Solved in : https://github.com/nmaguirre/riocuartobandasderock/commit/9c7d3235ae40dc16b068fdf846180b0086b5beb5

**Comment by adriangalfioni** [comment]
Implementation done in 824bcd5c68bcbb24348db79ec67f255d2b715311
Test done in 026b93d75a071d4294ab2aa2973ca777fa1183f0
