### ISSUE TITLE
Add features of Band

### ISSUE THREAD

**Issue by ezedepetris** [nmaguirre/riocuartobandasderock#39]
add all feature of Band, and the implementation

**Comment by ezedepetris** [comment]
feature of delete band in this rev [09f7bba]

**Comment by lbuttignol** [comment]
feature AddBand complete on this commit [ 8c4bdad ]

**Comment by lbuttignol** [comment]
Delete old features file on this rev 244e107

**Comment by gamassimino** [comment]
1670ac2
23026b1
4f1fd0b
