### ISSUE TITLE
add all feature of Artist

### ISSUE THREAD

**Issue by letcharren** [nmaguirre/riocuartobandasderock#40]
add all feature of Artist, and the implementation

**Comment by juanpabloRV** [comment]
When the Gherkin scenario is executed, an error occurs on line 7 of feature and on line 43 of step_definition.rb because expect 201as code RESTClient really return a 409. fix them.

**Comment by juanpabloRV** [comment]
idem to previous comment at line 14 and line 39 add Artist.feature of step_definition.rb

**Comment by juanpabloRV** [comment]
"Scenario: Add a new artist with the the same name, surname and nickname that an artist that store before in the databasee" --> Fix redaction.

**Comment by juanpabloRV** [comment]
When the Gherkin scenario is executed (findArtist.feature), an error occurs on line 19 of feature and on line 39 of step_definition.rb because expect 201as code RESTClient really return a 409. fix them.

**Comment by juanpabloRV** [comment]
When the Gherkin scenario is executed (findArtist.feature), an error occurs on line 23 of feature and on line 39 of step_definition.rb because expect 201as code RESTClient really return a 409. fix them.

**Comment by juanpabloRV** [comment]
When the Gherkin scenario is executed (findArtist.feature), an error occurs on line 27 of feature and on line 39 of step_definition.rb because expect 201as code RESTClient really return a 409. fix them.

**Comment by juanpabloRV** [comment]
When the Gherkin scenario is executed (findArtist.feature), an error occurs on line 31 of feature and on line 39 of step_definition.rb because expect 201as code RESTClient really return a 409. fix them.

**Comment by juanpabloRV** [comment]
When the Gherkin scenario is executed (findArtist.feature), an error occurs on line 36 of feature and on line 39 of step_definition.rb because expect 201as code RESTClient really return a 409. fix them.

**Comment by juanpabloRV** [comment]
When the Gherkin scenario is executed (findArtist.feature), an error occurs on line 40 of feature and on line 39 of step_definition.rb because expect 201as code RESTClient really return a 409. fix them.

**Comment by juanpabloRV** [comment]
When the Gherkin scenario is executed (findArtist.feature), an error occurs on line 49 of feature and on line 39 of step_definition.rb because expect 201as code RESTClient really return a 409. fix them.

**Comment by letcharren** [comment]
finish in commit in 9a2c694 fix response codes in steps in commit 4840fc8

**Comment by juanpabloRV** [comment]
In scenario in the last stage of addArtist.feature:

Scenario: Add a new artist with the the same name, surname and nickname that an artist that store before in the database
		Given that the artist's database have one artist with name "Matias" and surname "Serra" and nickname ""
        When I add an artist with name "Matias" and surname "Serra" and nickname ""
        Then the artist's database should have 1 entry
        And the entry should have name "Matias" and surname "Serra"

You wanted (i think) to prove that: if an artist already exists, see the application what happens.

The problem is that the file step_definitions.rb, in lines 54 to 57 in this case, for any query ALWAYS expects a code 201 and this scenario in particular, return code 409. 

See how to solve this.

Regards.

**Comment by letcharren** [comment]
@juanpabloRV  Juan Pablo this problem was solved before, we talked on Friday. Someone outside this issue change the code. When I can, I will fix it.

**Comment by letcharren** [comment]
fix in commit 4840fc8 and resolved in commit ec2866a
