### ISSUE TITLE
add all features of Song

### ISSUE THREAD

**Issue by guttlein** [nmaguirre/riocuartobandasderock#41]
add all features of Song and implementation

**Comment by DanielSanchez94** [comment]
mister Cap and mister Emi, I request to resolve the implementation of features, urgently. kiss

**Comment by juanpabloRV** [comment]
Int the file: deleteSong.feature at line 21.

Scenario: I delete a song that doesn't exist
	Given That the song with the name "Jijiji"
	And The database is empty
	When I delete a song with the name "Jijij"
	The An exception is thrown             --------------------> parse error, change "The" for "Then"
	And the database is empty

**Comment by juanpabloRV** [comment]
In the file SongController.java at line151 to 166 the method:

public String createSong(Request req,Response res){
		/*if((req.queryParams("name")=="") && (req.queryParams("duration")=="")){
			res.status(400);
			return "Request invalid";
		}
		Song song = new Song(req.queryParams("name"), Integer.parseInt(req.queryParams("duration")));
		boolean result = songDao.addSong(song);
		if (result) {
			res.status(201);
			return "Success";
		}
		else {
			return "Failed";
		}*/
		return "gorra resolve esto jaja";        -----------> WHAT MEANS???!!!!!!
	}

**Comment by juanpabloRV** [comment]
In scenario in the last stage of addSong.feature:

Scenario: Add a new song on an empty song's database 
        Given that the song's database is empty
        When I add a song with name "Stairway to Heaven" and duration "400"
        Then the song's database should have 1 entry
        And the entry should have name "Stairway to Heaven" and duration "400" 

You wanted to prove that: if an artist not exists, see the application add them.

The problem is that the file step_definitions.rb, in lines 107 to 110 in this case, for any query ALWAYS expects a code 201 and this ecenario in particular, return code 200. 

See how to solve this.

Regards.

**Comment by juanpabloRV** [comment]
In the file step_definitions.rb at line 114 I see:

String s = 'http://localhost:4567/song/findby' + atributo + '/' + valor

and on the other hand Boostrap at line 94, expect:

get("/song/findbyname/:name",(req,res)->songController.getSongByName(req,res));

it does not match. Fix it.

Regards.
