### ISSUE TITLE
adding new scenarios to addAlbum feature

### ISSUE THREAD

**Issue by gabybertorello** [nmaguirre/riocuartobandasderock#42]
adding new scenarios to addAlbum.

**Comment by gabybertorello** [comment]
progress on rev. 584b5f7

**Comment by gabybertorello** [comment]
adjustments on rev. 4ae187a

**Comment by juanpabloRV** [comment]
The scenario has syntax errors, caused by not properly resolve conflicts in git. Please resolve them.

**Comment by orevitnoonairam** [comment]
Git conflicts fixed, adjustments and progress on rev. 3cecea7
