### ISSUE TITLE
Model.Song is missing

### ISSUE THREAD

**Issue by fmollea** [nmaguirre/riocuartobandasderock#5]
Class Model.song is missing. This class is a representation of a song interpreted by Rio Cuarto's band.

The class contains the attributes:

	* id represents the id of the song
	* nameSong represents the name of the song
	* genere represents the genere of the song
	* performBy represents the bands from Rio Cuarto who played this song
	* duration represents the duration of this song
	* author represents the author who composed the song
	* album represents the album where the song belongs
	
Mehods: geters and seters of all attibutes and Constructor of the class.

The class should have test checking its expected functionality in a number of different scenarios. Statement coverage is expected from the tests of this routine.

**Comment by letcharren** [comment]
missing description

**Comment by fernando13** [comment]
issue working progress cf6ce98

**Comment by fernando13** [comment]
latest 1566d26

**Comment by fernando13** [comment]
480fd2b

**Comment by fernando13** [comment]
690be76
