### ISSUE TITLE
Implementation of Album missing

### ISSUE THREAD

**Issue by orevitnoonairam** [nmaguirre/riocuartobandasderock#7]
Implementation of the class Album that modeled an music album with the most relevant information about it.

**Comment by dmatiasr** [comment]
AlbumDao Issue information #14

**Comment by orevitnoonairam** [comment]
progress 26a8b26

**Comment by orevitnoonairam** [comment]
progress c581550

**Comment by orevitnoonairam** [comment]
Javadoc comments 4c4985c

**Comment by gabybertorello** [comment]
correction 6c3f70c

**Comment by orevitnoonairam** [comment]
deleting unnecesary fields on rev. 30c18eb

**Comment by orevitnoonairam** [comment]
Linking with db on rev. db83c10

**Comment by orevitnoonairam** [comment]
Javadoc comments corrected on rev. 7625126
